# Generated by Django 3.0.9 on 2021-10-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Agri-food', 'Agri-food'), ('Building materials', 'Building materials'), ('Hardware items', 'Hardware items'), ('Sanitary facilities', 'Sanitary facilities'), ('Hygienic & cleaning products', 'Hygienic & cleaning products'), ('Cosmetic products', 'Cosmetic products')], default='', max_length=50)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%y/%m/%d/')),
                ('name', models.CharField(default='', max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
