# Generated by Django 3.0.9 on 2021-10-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/%y/%m/%d/'),
        ),
    ]
