# Generated by Django 3.0.9 on 2021-09-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tel',
            field=models.CharField(default=29003487, max_length=15),
            preserve_default=False,
        ),
    ]
