# Generated by Django 3.0.9 on 2021-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210926_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
